### PR TITLE
Update sandbox environment condition does not depend on debug mode

### LINKED ISSUE #11: Payment Token is Invalid
I'm using this package to handle midtrans payment but i got this error, can you help me?
Using the redirection url from midtrans the snap token is fine though.

Simulator Screen Shot - iPhone 13 Pro - 2022-07-30 at 09 27 10

### PR DESCRIPTION
**Pull request by ferysyukur**
Hi @tomykho, I'm trying to make sandbox environment works in ios. Because I'm using multiple scheme in ios. So I tried to check base  if url is contain sandbox, so we still can make sandbox environment works ios.

Close #11

### CODE REVIEW

**Comment by tomykho** [comment]
I don't think hardcode checking merchant url is a good solution. Midtrans might rename the URL in future.
I think passing `sandbox: true` directly from Flutter will be much better.

**Comment by tomykho** [comment]
Also can you let me know why `DEBUG` is not working?
I am also using multi schemes/flavors on my apps too.
It will be better if you can provide me `print` result of `DEBUG` or example project of using multiple schemes.

**Comment by tomykho** [comment]
I think most people missed `DEBUG` flag during scheme setup process.
https://stackoverflow.com/questions/479531/how-do-i-declare-a-debug-only-statement

**Comment by ferysyukur** [comment]
Ah you're right. I think we can add sandbox true in flutter like you said. So we still can use without debug flag. I close this PR.

**Comment by tomykho** [comment]
Just to let you know, I am currently making new Midtrans package for dart and it will support other platforms like Windows, Linux, and Web. I will archive this package after that.

**Pull request closed without merging**
